version: '3'

# Dandelion
services:
  dandelion:
    image: forge.aeris-one.fr/dandelion/dandelion:stable
    volumes:
      - ./data/dandelion:/app/data:rw
    container_name: dandelion
    restart: always
    networks:
      - dandelion
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_USER=dandelion
      - DATABASE_NAME=dandelion
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DISCORD_BOT_TOKEN=your-bot-token
      - DISCORD_APPLICATION_ID=your-application-id
      - DISCORD_OWNER_ID=your-discord-user-id
      - DISCORD_MAIN_GUILD_ID=your-support-guild-id
      - DISCORD_STATUS_CHANNEL_ID=your-status-channel-id
      - ENVIRONMENT=production

# MySQL
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    networks:
      - dandelion
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=dandelion
      - MYSQL_USER=dandelion
      - MYSQL_PASSWORD=password
      - TZ=Europe/Paris
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s

networks:
  dandelion:
    driver: bridge